name: Lint checks

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            ./src
          github_token: ${{ secrets.GITHUB_TOKEN }}
